name: Robot API Tests
on:
  push:
    branches: [main]
  pull_request:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run robot tests
        run: |
          robot -d results -v ENV:qa Tests/

      - name: upload robot report
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: results/